- name: disable default redis
  command: dnf module disable redis -y

- name: enable redis
  command: dnf module enable redis:7 -y

- name: installing redis
  package: 
    name: redis
    state: present

- name: allow traffic to all
  replace:
    path: /etc/redis/redis.conf 
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: replace the text
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: 'protected-mode no'

- name: starting and enable redis
  service:
    name: redis
    state: started
    enabled: yes