  - name: installing mysql
    package: 
      name: mysql-server
      state: present
  
  - name: start and enabling mysql
    service:
      name: mysqld
      state: started
      enabled: yes

  # - name: get secret from Secrets Manager
  #   debug:
  #     msg: "{{ lookup('amazon.aws.aws_secret', 'roboshop/mysql', region='us-east-1') }}"

  # - name: prin the password
  #   debug:
  #     msg: "{{ root_password.mysql_root_password }}"

  - name: creating user and password
    command: mysql_secure_installation --set-root-pass "{{ root_password.mysql_root_password  }}"