- name: daemon reload
  systemd_service:
    name: "{{ component }}"
    daemon_reload: true
- name: start & enable catalouge
  service:
    name: "{{ component }}"
    state: restarted
    enabled: yes