- name: disabling nodejs
  command: dnf module disable nodejs -y
- name: enableing node js
  command: dnf module enable nodejs:20 -y
- name: insatlling nodejs
  package:
    name: nodejs
    state: present
- name: craete robshop system user
  user: 
    name: roboshop
    comment: roboshop systemuser 
    system: true
    home: /app
    shell: /sbin/nologin
- name: remove app directory
  file: 
    path: /app
    state: absent
- name: remove file
  file:
    path: /tmp/catalouge.zip
    state: absent
- name: creating directory
  file:
    path: /app
    state: directory
- name: downloading file
  get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalouge.zip
- name: extracting the file
  unarchive:
    src: /tmp/catalouge.zip
    dest: /app
    remote_src: yes
# - name: changing the directory
#   command: cd /app
- name: installing the npm
  command: npm install
  args: 
    chdir: /app 
- name: copy catalouge service
  template:
    src: catalouge.service.j2
    dest: /etc/systemd/system/catalogue.service
- name: copy mongo repo
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: installing mongo db
  package: 
    name: mongodb-mongosh
    state: present
- name: check catalogue schema exist ot not
  shell: mongosh --host "{{ MONGODB_HOST }}" --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
  tags:
    - mongodb
- name: print catalogue_output
  debug: 
      msg: "{{ catalogue_output }}"
  tags:
    - mongodb
- name: load products
  shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: catalogue_output.stdout | int < 0
  tags:
    - mongodb
# - name: load the data into database
#   shell: mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js
- name: daemon reload
  systemd_service:
    name: catalouge
    daemon_reload: true
- name: start & enable catalouge
  service:
    name: catalogue
    state: restarted
    enabled: yes